### ISSUE TITLE
First release

### ISSUE THREAD

**Issue by ngtk** [ngtk/open_api_annotator#1]
## Todo
- [x] Write readme
- [x] Enable to filter path
- [x] Enable to configure base controller
- [x] Enable to configure base serializer
- [x] Add changelog
- [x] Add bump gem

## Draft of README
- Description
- Usage

## Description
OpenApiAnnotator realizes to generate OpenApi spec by annotating to controllers and serializers.
If you use ActiveModelSerializer, this is the best to generate OpenAPI spec.

## Usage
Annotating controllers and serializers, you can generate OpenAPI spec file from these.
Things you have to do are three below:

1. Configure API meta information
1. Annotate controllers
1. Annotate serializers

### 1. Configure API meta information
You have to set API meta information like:

```rb
# config/initializers/open_api_annotator.rb
OpenApiAnnotator.configure do |config|
  config.info = OpenApi::Info.new(title: "Book API", version: "1")
  config.destination_path = Rails.root.join("api_spec.yml")
  config.path_regexp = /\Aapi\/v1\// # If you want to restrict a path to create
end
```

### 2. Annotate controller
To define an entity of an endpoint, call the method `endpoint` in the previous line of an action method. It takes entity expression as the first arg. Entity expression is a model class or an array that contains only one model class.

```rb
class Api::V1::BooksController
  endpoint [Book] # 👈It means an array of Book
  def index
    books = Book.limit(10)
    render json: books
  end

  endpoint Book # 👈Just a Book
  def show
    book = Book.find(params[:id])
    render json: book
  end

  endpoint Book # 👈Just a Book
  def update
     book = Book.find(params[:id])
     book.update!(book_params)
     render json: book
  end
end
```

### 3. Annotate serializer
To define an schema in components, set `type`, `format`, `nullable` as each field option.

```rb
class BookSerializer < ApplicationSerializer
  attribute :title, type: :string, nullable: false
  attribute :published_at, type: :string, format: :"date-time", nullable: true

  has_many :authors, type: [Author], nullable: false
  has_one :cover_image, type: CoverImage, nullable: true
  belongs_to :publisher, type: Publisher, nullable: false
end
```

**Comment by ngtk** [comment]
done! ✨
